# Generated by Django 3.2.4 on 2021-06-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='court',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='booking.court'),
            preserve_default=False,
        ),
    ]
