# Generated by Django 3.1.7 on 2021-06-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_event_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='isTennis',
            field=models.BooleanField(default=False),
        ),
    ]
