# Generated by Django 3.1.7 on 2021-06-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
